/**
 * Run Registry Types
 * 
 * Types for the run registry that tracks all pipeline runs.
 * This enables history views and retention management.
 * 
 * @module types/runRegistry
 */

import type { PipelineType, RunStatus, TemporalMode } from './pipelineRun';

// ============================================================================
// Run Registry Entry
// ============================================================================

/**
 * Options used when starting a run
 */
export interface RunOptions {
    /** Sample ID (production) */
    sample?: string;
    /** Script path (narrative) */
    script?: string;
    /** Temporal regularization mode */
    temporal?: TemporalMode;
    /** Verbose logging enabled */
    verbose?: boolean;
    /** Dry run mode */
    dryRun?: boolean;
}

/**
 * Links to artifacts generated by the run
 */
export interface RunArtifacts {
    /** Path to run summary JSON */
    summaryJson?: string;
    /** Path to run summary markdown */
    summaryMd?: string;
    /** Path to output video */
    video?: string;
    /** Path to original video (before temporal smoothing) */
    originalVideo?: string;
    /** Path to vision QA results */
    visionQa?: string;
    /** Path to benchmark JSON */
    benchmarkJson?: string;
    /** Path to benchmark markdown report */
    benchmarkMd?: string;
    /** Path to manifest file */
    manifest?: string;
    /** Path to run directory */
    runDir?: string;
    /** Path to final concatenated video (narrative) */
    finalVideo?: string;
}

/**
 * A single entry in the run registry
 */
export interface RunRegistryEntry {
    /** Unique run identifier */
    runId: string;
    /** Type of pipeline run */
    type: PipelineType;
    /** Current run status */
    status: RunStatus;
    /** When the run started (ISO string) */
    startedAt: string;
    /** When the run finished (ISO string, null if still running) */
    finishedAt: string | null;
    /** Duration in milliseconds (null if still running) */
    durationMs: number | null;
    /** Run options used */
    options: RunOptions;
    /** Artifact links */
    artifacts: RunArtifacts;
    /** Warnings from the run */
    warnings: string[];
    /** Validation warnings captured before start */
    validationWarnings?: string[];
    /** Step timing summaries (lightweight) */
    stepTimings?: Array<{
        stepId: string;
        durationMs: number;
        status: 'complete' | 'failed' | 'running';
    }>;
    /** Identifier string (e.g., "production-qa-golden (sample-001-geometric)") */
    identifier: string;
    /** Pipeline ID (production) */
    pipelineId?: string;
    /** Vision QA status (production) */
    visionQaStatus?: string;
    /** Benchmark status */
    benchmarkStatus?: 'available' | 'missing';
}

// ============================================================================
// Run Registry File
// ============================================================================

/**
 * The full run registry file structure
 * Stored at: data/run-registry.json
 */
export interface RunRegistry {
    /** Schema version for forward compatibility */
    version: '1.0';
    /** All run entries, newest first */
    runs: RunRegistryEntry[];
    /** Last updated timestamp */
    lastUpdated: string;
}

// ============================================================================
// Run History (UI Consumable)
// ============================================================================

/**
 * A simplified run entry for UI history view
 */
export interface RunHistoryEntry {
    /** Unique run identifier */
    runId: string;
    /** Type of pipeline run */
    type: PipelineType;
    /** Current run status */
    status: RunStatus;
    /** When the run started (ISO string) */
    startedAt: string;
    /** When the run finished (ISO string, null if still running) */
    finishedAt: string | null;
    /** Duration in milliseconds */
    durationMs: number | null;
    /** Identifier string */
    identifier: string;
    /** Sample ID (production) or Script path (narrative) */
    sample?: string;
    /** Whether temporal regularization was applied */
    temporalApplied?: boolean;
    /** Key warnings (first few) */
    keyWarnings: string[];
    /** Total warning count */
    warningCount: number;
    /** Artifact links */
    artifacts: RunArtifacts;
    /** Step timing summaries (lightweight) */
    stepTimings?: Array<{
        stepId: string;
        durationMs: number;
        status: 'complete' | 'failed' | 'running';
    }>;
    /** Validation warnings captured before start */
    validationWarnings?: string[];
    /** Age in milliseconds */
    ageMs: number | null;
    /** Vision QA status (production) */
    visionQaStatus?: string;
}

/**
 * Run history file for UI consumption
 * Stored at: public/run-history.json
 */
export interface RunHistoryFile {
    /** Schema version */
    version: '1.0';
    /** Recent runs (limited to last N, default 20) */
    runs: RunHistoryEntry[];
    /** Total count in registry (may be more than returned) */
    totalCount: number;
    /** Last updated timestamp */
    lastUpdated: string;
}

// ============================================================================
// Retention Policy
// ============================================================================

/**
 * Retention policy configuration
 */
export interface RetentionPolicy {
    /** Keep last N runs (0 = unlimited) */
    keepLastN?: number;
    /** Keep runs from last X days (0 = unlimited) */
    keepDays?: number;
    /** Paths to clean up */
    paths: {
        benchmarks: boolean;
        runSummaries: boolean;
        narratives: boolean;
        output: boolean;
        latestPointers: boolean;
        registryEntries: boolean;
    };
}

/**
 * Default retention policy (conservative)
 */
export const DEFAULT_RETENTION_POLICY: RetentionPolicy = {
    keepLastN: 50,
    keepDays: 30,
    paths: {
        benchmarks: true,
        runSummaries: true,
        narratives: true,
        output: false, // Don't auto-delete output by default
        latestPointers: false, // Don't delete latest pointers
        registryEntries: true,
    },
};

// ============================================================================
// Constants
// ============================================================================

/** Path to run registry file */
export const RUN_REGISTRY_PATH = 'data/run-registry.json';

/** Path to run history file (public, for UI) */
export const RUN_HISTORY_PATH = 'public/run-history.json';

/** Default number of runs to include in history */
export const DEFAULT_HISTORY_LIMIT = 20;
