export const FRAMING_OPTIONS = ["Bird's-Eye View", "Close-Up", "Cowboy Shot", "Establishing Shot", "Extreme Close-Up", "Full Shot", "High Angle", "Low Angle", "Insert Shot", "Medium Shot", "Over-the-Shoulder", "Point of View", "Two Shot", "Wide Shot", "Worm's-Eye View"];
export const MOVEMENT_OPTIONS = ["Arc Shot", "Crane/Jib Shot", "Dolly Zoom", "Dutch Tilt", "Follow Shot", "Handheld", "Majestic Sweep", "Pan", "Pull Out", "Push In", "Static Shot", "Steadicam", "Tilt", "Tracking Shot", "Whip Pan", "Zoom In/Out"];
export const LENS_OPTIONS = ["Anamorphic", "Bokeh", "Deep Focus", "Fisheye Lens", "Lens Flare", "Probe Lens", "Rack Focus", "Shallow Depth of Field", "Soft Focus", "Split Diopter", "Telephoto", "Tilt-Shift", "Wide-Angle"];
export const PACING_OPTIONS = ["Bullet Time", "Chaotic", "Cross-Cutting", "Fast-Paced", "Freeze Frame", "Graceful", "Jump Cut", "Long Take", "Montage", "Rhythmic Cutting", "Slow Motion", "Smash Cut", "Speed Ramp"];
export const LIGHTING_OPTIONS = ["Low-Key (Chiaroscuro)", "High-Key", "Backlight / Rim Light", "Golden Hour", "Neon Glow", "Hard Lighting", "Silhouette", "Gobo/Cookies", "Volumetric Lighting"];
export const MOOD_OPTIONS = ["Suspenseful", "Epic", "Gritty", "Dreamlike", "Tense", "Energetic", "Nostalgic"];
export const VFX_OPTIONS = ["Bleach Bypass", "Chromatic Aberration", "Color Grading (Teal & Orange)", "Day-for-Night", "Desaturated", "Film Grain", "Glitch Effect", "Glow/Bloom", "High Contrast", "Lens Dirt/Smudges", "Light Leaks", "Motion Blur", "Particle Effects", "Scanlines", "VHS Look", "Vignette"];
export const PLOT_ENHANCEMENTS_OPTIONS = ["Add Character Action", "Introduce Conflict", "Foreshadowing Moment", "Heighten Emotion", "Add Dialogue Snippet", "Reveal a Detail", "Introduce Sci-Fi Element", "Introduce Plot Twist"];
export const TRANSITION_OPTIONS = ["Cut", "Dissolve", "Wipe", "Match Cut", "J-Cut", "L-Cut", "Whip Pan", "Glitch Effect", "Fade to Black", "Iris In/Out", "Smash Cut"];


export const CINEMATIC_TERMS: Record<string, Record<string, string>> = {
  framing: {
    "Bird's-Eye View": "Shot from directly overhead, creating a god-like perspective and showing the subject in relation to their environment.",
    "Close-Up": "Focuses on a specific detail, usually a character's face, to show emotion or reaction.",
    "Cowboy Shot": "A shot framed from mid-thigh up, originally used in Westerns to show a character's gun holster.",
    "Establishing Shot": "A very wide shot at the beginning of a scene to establish the setting and context.",
    "Extreme Close-Up": "Magnifies a very small detail, like an eye or a written word, for dramatic effect.",
    "Full Shot": "Shows the entire subject from head to toe, with some of the surrounding environment visible.",
    "High Angle": "The camera is placed above the subject, looking down, which can make the subject seem small or vulnerable.",
    "Low Angle": "The camera is placed below the subject, looking up, which can make the subject seem powerful or imposing.",
    "Insert Shot": "A close-up of a significant object or detail that the character is looking at or interacting with.",
    "Medium Shot": "Shows the subject from the waist up, balancing detail with some of the surrounding context.",
    "Over-the-Shoulder": "A shot from behind one person's shoulder, looking at another person. Common in conversations.",
    "Point of View": "Shows what a character is looking at, as if from their own eyes.",
    "Two Shot": "A shot with two characters in the frame.",
    "Wide Shot": "Shows the subject in their environment, providing context and scale.",
    "Worm's-Eye View": "An extreme low-angle shot from ground level, looking up.",
  },
  movement: {
    "Arc Shot": "The camera moves in a circular or semi-circular path around the subject, often to reveal different aspects of the scene.",
    "Crane/Jib Shot": "The camera is mounted on a crane, allowing for high-angle and dramatic sweeping motions.",
    "Dolly Zoom": "The camera moves forward or backward on a dolly while the lens zooms in the opposite direction, creating a disorienting effect.",
    "Dutch Tilt": "The camera is tilted on its side, creating a skewed, unsettling image.",
    "Follow Shot": "The camera follows a moving subject, keeping them in the frame.",
    "Handheld": "The camera is held by the operator, resulting in a shaky, realistic, and often urgent feel.",
    "Majestic Sweep": "A slow, grand, sweeping camera movement, often using a crane or drone, to reveal the scale of a location.",
    "Pan": "The camera swivels horizontally from a fixed position.",
    "Pull Out": "The camera moves backward, revealing more of the scene (similar to Dolly Out).",
    "Push In": "The camera moves forward, getting closer to the subject (similar to Dolly In).",
    "Static Shot": "The camera remains completely still, without any movement.",
    "Steadicam": "A camera stabilizing mount that allows for smooth, fluid motion even when the operator is moving.",
    "Tilt": "The camera swivels vertically from a fixed position.",
    "Tracking Shot": "The camera moves alongside a moving subject, often on a track or dolly.",
    "Whip Pan": "A very fast pan that blurs the image, used as an energetic transition.",
    "Zoom In/Out": "The camera lens changes focal length to magnify or de-magnify the subject, without the camera itself moving.",
  },
  lens: {
    "Anamorphic": "A lens that creates a widescreen aspect ratio and distinctive horizontal lens flares and oval bokeh.",
    "Bokeh": "The aesthetic quality of the blur in the out-of-focus parts of an image.",
    "Deep Focus": "Everything in the frame, from the foreground to the background, is in sharp focus.",
    "Fisheye Lens": "An ultra-wide-angle lens that produces strong visual distortion, creating a wide panoramic or hemispherical image.",
    "Lens Flare": "Streaks of light that appear when a bright light source is aimed at the lens.",
    "Probe Lens": "A long, thin lens used for getting extreme close-ups in tight spaces or creating unique, floating perspectives.",
    "Rack Focus": "Changing the focus of the lens from one subject to another within a single shot.",
    "Shallow Depth of Field": "Only a small part of the image is in focus, while the background and foreground are blurred.",
    "Soft Focus": "A slightly blurred effect, often used for dreamlike or romantic scenes.",
    "Split Diopter": "A special lens that allows two different planes of distance to be in focus simultaneously.",
    "Telephoto": "A lens with a long focal length that compresses the background, making distant objects appear closer.",
    "Tilt-Shift": "A lens that can be tilted and shifted to control perspective and create a miniature-world effect.",
    "Wide-Angle": "A lens with a short focal length that captures a wide field of view and can distort perspective at the edges.",
  },
  pacing: {
    "Bullet Time": "An extreme slow-motion effect where the camera appears to move around a subject at normal speed while the action is slowed.",
    "Chaotic": "Fast, disorienting cuts and movement to create a sense of panic or confusion.",
    "Cross-Cutting": "Alternating between two or more scenes that are happening simultaneously but in different locations.",
    "Fast-Paced": "Quick edits and rapid action to create excitement and energy.",
    "Freeze Frame": "A single frame of film is held for a period of time, pausing the action.",
    "Graceful": "Smooth, flowing camera movements and longer takes to create a sense of elegance.",
    "Jump Cut": "An abrupt cut between two shots of the same subject from slightly different angles, creating a jarring effect.",
    "Long Take": "A single, uninterrupted shot that lasts for an extended period of time.",
    "Montage": "A sequence of short shots edited together to condense space, time, and information.",
    "Rhythmic Cutting": "Editing shots to a specific beat or rhythm, often in sync with music or a recurring sound.",
    "Slow Motion": "Slowing down the speed of the action to emphasize movement or create a dramatic effect.",
    "Smash Cut": "An abrupt and often jarring transition from one scene to another, usually from quiet to loud or vice-versa.",
    "Speed Ramp": "Changing the speed of a clip from slow to fast, or vice versa, within a single shot.",
  },
  lighting: {
    "Low-Key (Chiaroscuro)": "High-contrast lighting with deep shadows and a dark overall mood. Creates drama and mystery.",
    "High-Key": "Bright, even lighting with few shadows. Creates a positive, cheerful, or sterile atmosphere.",
    "Backlight / Rim Light": "Light placed behind the subject, creating a glowing edge or halo effect that separates them from the background.",
    "Golden Hour": "The period shortly after sunrise or before sunset, known for its warm, soft, and cinematic light.",
    "Neon Glow": "Vibrant, colorful light from neon signs, often used in cyberpunk or urban noir settings.",
    "Hard Lighting": "Creates sharp, well-defined shadows and high contrast. Can feel intense or dramatic.",
    "Silhouette": "The subject is seen as a black shape against a bright background, concealing detail and creating mystery or drama.",
    "Gobo/Cookies": "Using a stencil (gobo or 'cookie') to cast patterned shadows, like light through window blinds or leaves.",
    "Volumetric Lighting": "Making light beams visible, like dusty rays of light in a room or misty god rays, adding depth and atmosphere.",
  },
  mood: {
    "Suspenseful": "Creating a feeling of anticipation, tension, and uncertainty about what is going to happen.",
    "Epic": "Conveying a sense of grand scale, heroism, and monumental events.",
    "Gritty": "A raw, realistic, and often bleak style. Unpolished and intense.",
    "Dreamlike": "Surreal, ethereal, and often illogical, as if in a dream.",
    "Tense": "High-stakes, nerve-wracking atmosphere filled with conflict and pressure.",
    "Energetic": "Fast-paced, vibrant, and full of life and movement.",
    "Nostalgic": "A sentimental longing or wistful affection for a period in the past.",
  },
  vfx: {
    "Bleach Bypass": "A film developing effect that reduces saturation and increases contrast and grain, creating a stark, harsh look.",
    "Chromatic Aberration": "A color distortion effect where colors fringe at the edges of objects, often used for a lo-fi or disoriented look.",
    "Color Grading (Teal & Orange)": "A popular color scheme in modern cinema that pushes cool tones toward teal and skin tones toward orange.",
    "Day-for-Night": "Shooting during the day but using filters and post-production to simulate nighttime.",
    "Desaturated": "Muted, washed-out colors, creating a bleak or somber mood.",
    "Film Grain": "A textural, grainy look that emulates the look of traditional film stock.",
    "Glitch Effect": "Digital errors and distortions used for stylistic effect, common in sci-fi and tech themes.",
    "Glow/Bloom": "Bright areas of the image bleed into darker areas, creating a soft, hazy, or ethereal look.",
    "High Contrast": "Strong differences between the bright and dark areas of the image, with very few mid-tones.",
    "Lens Dirt/Smudges": "Simulating a dirty camera lens to add realism or a gritty texture.",
    "Light Leaks": "Strips of bright, often colorful light that simulate accidental light exposure on film.",
    "Motion Blur": "The blurring of moving objects, which can be added to enhance the sense of speed.",
    "Particle Effects": "Computer-generated effects like dust, smoke, fire, or rain.",
    "Scanlines": "Horizontal lines that mimic the look of an old CRT television screen.",
    "VHS Look": "Degraded, low-fidelity video quality that emulates the look of a VHS tape.",
    "Vignette": "Darkening the corners of the frame to draw focus to the center.",
  },
  plotEnhancements: {
    "Add Character Action": "Introduce a specific action performed by a character to advance the plot or reveal their personality.",
    "Introduce Conflict": "Create a new obstacle, disagreement, or challenge for the characters.",
    "Foreshadowing Moment": "Subtly hint at a future event or revelation.",
    "Heighten Emotion": "Amplify the emotional state of a character through their expression, action, or environment.",
    "Add Dialogue Snippet": "Insert a brief line of dialogue that reveals crucial information or character.",
    "Reveal a Detail": "Show the audience an important object or detail that was previously unseen or unnoticed.",
    "Introduce Sci-Fi Element": "Add a piece of futuristic technology, an alien object, or a sci-fi concept to the scene.",
    "Introduce Plot Twist": "Introduce a radical, unexpected change in the direction or expected outcome of the plot.",
  },
  transitions: {
    "Cut": "The most common transition, an instant change from one shot to another.",
    "Dissolve": "One shot gradually fades out while another fades in, often used to show passage of time.",
    "Wipe": "A line or shape moves across the screen, pushing one shot off and revealing the next.",
    "Match Cut": "Cuts from one shot to another by matching action or composition, creating a strong link.",
    "J-Cut": "The audio from the next scene begins before the video changes.",
    "L-Cut": "The audio from the current scene continues into the next shot.",
    "Whip Pan": "A very fast pan that blurs the image, creating a sense of energy and speed.",
    "Glitch Effect": "A digital distortion effect used as a stylistic transition.",
    "Fade to Black": "The image gradually fades to a black screen, often used to signify an ending.",
    "Iris In/Out": "A circular mask closes in (out) or opens up (in) on a shot, a classic, stylized transition.",
    "Smash Cut": "An abrupt and often jarring transition from one scene to another, usually from quiet to loud or vice-versa.",
  }
};